.TH PATHSHORTENER "1" "2021" "INFO MONO" "User Commands"
.SH NAME
PATHSHORTENER \- File system's path shortener
.SH SYNOPSIS
.B mk ITEMS
.SH DESCRIPTION
PATHSHORTENER is a file system's path shortener.
.SH ENVIRONMENT VARIABLES
\fBPATHSHORTENER_TRUNCATION_LENGTH\fR
The number of parent folders that the current directory should be truncated to
\fBPATHSHORTENER_SHORT_LENGTH\fR
The number of characters to display in truncated paths
\fBPATHSHORTENER_TRUNCATION_SYMBOL\fR
The symbol to prefix to truncated paths
\fBPATHSHORTENER_HOME_SYMBOL\fR
The symbol indicating home directory
.SH REPORTING BUGS
Report bugs to https://github.com/NNBnh/info-mono/issues
